### ISSUE TITLE
Undefined method in Grid setColums()

### ISSUE THREAD

**Issue by cynicbox** [spring-guides/gs-crud-with-vaadin#2] opened 2016-01-25 10:57 UTC
Next lines can fix it
grid.addColumn("id");
grid.addColumn("firstName");
grid.addColumn("lastName");

**Comment by gregturn** [comment] 2016-01-25 15:24
@cynicbox I don't get what the problem is. When I run "mvn clean spring-boot:run" the app runs as expected.

**Comment by tnock** [comment] 2016-02-06 22:54
@gregturn same problem here. Using your setup i end up with a Grid class from _vaadin-server-7.4.4.jar_ and that simply does not have a _setColumns_ method.
Solution of @cynicbox works.
Anyway, nice tutorial :-)

**Comment by cynicbox** [comment] 2016-02-07 12:13
Thanks god I'm sane ;) But @gregturn  is right too. I cloned this repo and everything works fine. It is a mystery.

**Comment by mstahv** [comment] 2016-03-11 08:10
I think the issue is you only added vaadin-spring-boot-starter, not the vaadin-bom overriding the Vaadin version in use? Are you using Maven or Gradle? 

Maybe we should change the wording "Additionally, you might want to override the used Vaadin version..." to such that it suggests that more strongly. Or/and just update the vaadin-spring-boot-starter with the latest Vaadin version.

**Comment by gregturn** [comment] 2016-03-11 15:28
@mstahv Well, if the issue is not reproducible, I suggest we close it. However, if you think using vaadin's BOM is standard procedure, would you like to add it to the maven and gradle builds and also document it in the guide?

**Closed** 2016-03-11 17:34 UTC
